# Generated by Django 5.2.8 on 2026-01-12 10:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Ex: iPhone 17 Pro, T-shirt Cotton White', max_length=200, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(999999.99)], verbose_name='Price')),
                ('description', models.TextField(help_text='Detailed product description for costumers', verbose_name='Description')),
                ('image', models.ImageField(blank=True, help_text='Optional product image (JPG/PMG)', null=True, upload_to='products/%Y/%m/', verbose_name='Product Image')),
                ('is_available', models.BooleanField(default=True, help_text='Whether product is available for purchase', verbose_name='Available')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Number of units in warehouse', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='Stock')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'is_available'], name='shop_produc_categor_b360d9_idx'), models.Index(fields=['-created_at'], name='shop_produc_created_ddfb00_idx')],
            },
        ),
    ]
