# Generated by Django 5.2.8 on 2026-01-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_slug_product_slug_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Ex: John', max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Ex: Kean', max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(db_index=True, help_text='Ex: john@example.com', max_length=255, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Optional phone number', max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(help_text='Full street address', verbose_name='Street Address')),
                ('postal_code', models.CharField(help_text='ZIP or postal code', max_length=20, verbose_name='Postal Code')),
                ('city', models.CharField(db_index=True, help_text='City name', max_length=100, verbose_name='City')),
                ('country', models.CharField(help_text='Country name', max_length=100, verbose_name='Country')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='shop_custom_email_5770bc_idx'), models.Index(fields=['city'], name='shop_custom_city_eb823a_idx'), models.Index(fields=['-created_at'], name='shop_custom_created_29a97e_idx')],
            },
        ),
    ]
