# Generated by Django 5.2.8 on 2026-01-13 11:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, help_text='Unique order identifier', max_length=50, unique=True, verbose_name='Order Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current order status', max_length=20, verbose_name='Status')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount in EUR', max_digits=10, verbose_name='Tax Amount')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shipping cost in EUR', max_digits=10, verbose_name='Shipping Cost')),
                ('notes', models.TextField(blank=True, help_text='Optional order notes or special requests', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('customer', models.ForeignKey(help_text='Customer information', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.customer', verbose_name='Customer')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user who placed the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_number'], name='shop_order_order_n_db1214_idx'), models.Index(fields=['status'], name='shop_order_status_63c2c0_idx'), models.Index(fields=['user', '-created_at'], name='shop_order_user_id_f8b1c9_idx'), models.Index(fields=['-created_at'], name='shop_order_created_da5569_idx')],
            },
        ),
    ]
